<a href="https://colab.research.google.com/github/asmit-ayank/UML501/blob/main/Assignment_1_UML501.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1 - Asmit Ayank (102497002)

**Q1: Questions on Basic NumPy Array**

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise

(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix

(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?


In [ ]:
import numpy as np

print("(a) Reverse array")
arr = np.array([1,2,3,6,4,5])
rev = arr[::-1]
print(rev)

print("\n(b) Flatten using two numpy built-ins")
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
flat1 = array1.flatten()    # method 1
flat2 = array1.ravel()      # method 2
print(flat1)
print(flat2)

print("\n(c) Compare arrays")
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print("Equal elementwise:", np.equal(arr1, arr2))
print("All equal?:", np.array_equal(arr1, arr2))

print("\n(d) Most frequent value and indices")
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

def most_freq_and_indices(a):
    vals, counts = np.unique(a, return_counts=True)
    maxcount = counts.max()
    modes = vals[counts == maxcount]
    indices = {int(m): np.where(a == m)[0].tolist() for m in modes}
    return modes.tolist(), maxcount, indices

print("x:", most_freq_and_indices(x))
print("y:", most_freq_and_indices(y))

print("\n(e) Sum operations on matrix (using np.matrix as given)")
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Sum all:", gfg.sum())
print("Row-wise sum:", np.array(gfg.sum(axis=1)).flatten())   # axis=1 -> sum rows
print("Column-wise sum:", np.array(gfg.sum(axis=0)).flatten())# axis=0 -> sum cols

print("\n(f) Linear algebra on n_array")
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
print("Diagonal sum (trace):", np.trace(n_array))
eigvals, eigvecs = np.linalg.eig(n_array)
print("Eigenvalues:", eigvals)
print("Eigenvectors (columns):\n", eigvecs)
print("Inverse:\n", np.linalg.inv(n_array))
print("Determinant:", np.linalg.det(n_array))

print("\n(g) Matrix multiply and covariance")
# (i)
p1 = np.array([[1,2],[2,3]])
q1 = np.array([[4,5],[6,7]])
prod1 = p1.dot(q1)
print("(g.i) product:\n", prod1)
# Covariance between flattened matrices (treat flattened matrices as variables)
cov1 = np.cov(p1.flatten(), q1.flatten())
print("(g.i) covariance matrix:\n", cov1)

# (ii)
p2 = np.array([[1,2],[2,3],[4,5]])
q2 = np.array([[4,5,1],[6,7,2]])
# To multiply p2 (3x2) with q2 (2x3) -> result (3x3)
prod2 = p2.dot(q2)
print("(g.ii) product shape", prod2.shape)
print(prod2)
cov2 = np.cov(p2.flatten(), q2.flatten())
print("(g.ii) covariance between flattened arrays:\n", cov2)

print("\n(h) inner, outer, Cartesian product")
x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1,5,0],[5,10,3]])
# inner: element-wise inner along last axis between corresponding rows:
inner = np.array([np.dot(x[i], y[i]) for i in range(min(x.shape[0], y.shape[0]))])
print("Inner (row-wise dot):", inner)
# outer: outer product of flattened arrays (this gives a large 6x6)
outer = np.outer(x.flatten(), y.flatten())
print("Outer shape:", outer.shape)
# Cartesian product: all pairs of vectors (rows) -> stack pair combinations
cartesian_pairs = np.array(np.meshgrid(np.arange(x.shape[0]), np.arange(y.shape[0]))).T.reshape(-1,2)
cartesian = [(x[i], y[j]) for i,j in cartesian_pairs]
print("Cartesian pairs (as (x_row, y_row)) count:", len(cartesian))
# example display first pair
print("First pair:", cartesian[0])

(a) Reverse array
[5 4 6 3 2 1]

(b) Flatten using two numpy built-ins
[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]

(c) Compare arrays
Equal elementwise: [[ True  True]
 [ True  True]]
All equal?: True

(d) Most frequent value and indices
x: ([1], np.int64(5), {1: [0, 5, 7, 8, 9]})
y: ([1, 3], np.int64(3), {1: [0, 1, 2], 3: [4, 8, 9]})

(e) Sum operations on matrix (using np.matrix as given)
Sum all: 45
Row-wise sum: [14 16 15]
Column-wise sum: [20  9 16]

(f) Linear algebra on n_array
Diagonal sum (trace): 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors (columns):
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001

(g) Matrix multiply and covariance
(g.i) product:
 [[16 19]
 [26 31]]
(g.i) covariance matrix:
 [[0.66666667 1.        ]
 [1.        

**Q2: Based on NumPy Mathematics and Statistics**

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values


In [ ]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])
print("Array:\n", array)

print("\n(a)(i) Element-wise absolute value")
print(np.abs(array))

print("\n(a)(ii) Percentiles")
# flattened
flat = array.flatten()
print("25th,50th,75th (flattened):", np.percentile(flat, [25,50,75]))

# for each column (axis=0)
print("25,50,75 per column:", np.percentile(array, [25,50,75], axis=0))

# for each row (axis=1)
print("25,50,75 per row:", np.percentile(array, [25,50,75], axis=1))

print("\n(a)(iii) Mean, median, std")
print("Flattened mean,median,std:", np.mean(flat), np.median(flat), np.std(flat))
print("Column wise mean,median,std:", np.mean(array,axis=0), np.median(array,axis=0), np.std(array,axis=0))
print("Row wise mean,median,std:", np.mean(array,axis=1), np.median(array,axis=1), np.std(array,axis=1))

print("\n(b) floor, ceil, trunc, round")
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("floor:", np.floor(a))
print("ceil: ", np.ceil(a))
print("trunc:", np.trunc(a))
print("round (default):", np.round(a))  # nearest integer
# show rounding with decimals if desired:
print("round 1 decimal:", np.round(a,1))

Array:
 [[ 1 -2  3]
 [-4  5 -6]]

(a)(i) Element-wise absolute value
[[1 2 3]
 [4 5 6]]

(a)(ii) Percentiles
25th,50th,75th (flattened): [-3.5 -0.5  2.5]
25,50,75 per column: [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
25,50,75 per row: [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

(a)(iii) Mean, median, std
Flattened mean,median,std: -0.5 -0.5 3.8622100754188224
Column wise mean,median,std: [-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
Row wise mean,median,std: [ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]

(b) floor, ceil, trunc, round
floor: [-2. -2. -1.  0.  1.  1.  3.]
ceil:  [-1. -1. -0.  1.  2.  2.  3.]
trunc: [-1. -1. -0.  0.  1.  1.  3.]
round (default): [-2. -2. -0.  0.  2.  2.  3.]
round 1 decimal: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]


**Q3: Based on Searching and Sorting**

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements

(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only

In [ ]:
import numpy as np

arr = np.array([10,52,62,16,16,54,453])
print("Original:", arr)

print("\n(a)(i) Sorted array")
sorted_arr = np.sort(arr)
print(sorted_arr)

print("\n(a)(ii) Indices of sorted array")
sorted_idx = np.argsort(arr)
print(sorted_idx)

print("\n(a)(iii) 4 smallest elements")
# using partition for efficiency
four_smallest = np.partition(arr, 3)[:4]   # not sorted; sort if needed
print("unsorted four smallest:", four_smallest)
print("sorted four smallest:", np.sort(four_smallest))

print("\n(a)(iv) 5 largest elements")
five_largest = np.partition(arr, -5)[-5:]
print("unsorted five largest:", five_largest)
print("sorted five largest:", np.sort(five_largest))

print("\n(b) integer-only and float-only from float array")
arr2 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
# integer elements only (exact integers)
is_int = np.isclose(arr2, np.round(arr2))  # safer with floats
ints = arr2[is_int]
floats = arr2[~is_int]
print("Integers only:", ints)
print("Non-integer floats only:", floats)

Original: [ 10  52  62  16  16  54 453]

(a)(i) Sorted array
[ 10  16  16  52  54  62 453]

(a)(ii) Indices of sorted array
[0 3 4 1 5 2 6]

(a)(iii) 4 smallest elements
unsorted four smallest: [10 16 16 52]
sorted four smallest: [10 16 16 52]

(a)(iv) 5 largest elements
unsorted five largest: [ 16  52  54  62 453]
sorted five largest: [ 16  52  54  62 453]

(b) integer-only and float-only from float array
Integers only: [1. 2. 3. 2.]
Non-integer floats only: [1.2 2.2]


**Q4:**

(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

(b) Load the saved file into jupyter notebook?

In [ ]:
# Colab cell: Q4 functions and demo
from PIL import Image
import numpy as np
import os

def img_to_array(path, out_prefix="saved_image"):
    """
    Reads image at `path`. Saves:
      - out_prefix + '.npy' : numpy binary (recommended)
      - out_prefix + '.txt' : text file (readable)
    Handles both grayscale and RGB images.
    Returns (array, saved_paths)
    """
    im = Image.open(path)
    arr = np.array(im)
    saved = {}
    # Save binary .npy
    npy_path = out_prefix + '.npy'
    np.save(npy_path, arr)
    saved['npy'] = npy_path

    # Save readable text form
    txt_path = out_prefix + '.txt'
    with open(txt_path, 'w') as f:
        # For RGB
        if arr.ndim == 3 and arr.shape[2] == 3:
            H,W,C = arr.shape
            # header
            f.write(f"{H} {W} {C}\n")
            # write pixel rows as R G B ... per pixel, row-major
            # each line corresponds to one image row, entries are triples separated by spaces
            for r in range(H):
                # flatten row to (W*3,) and write as whitespace-separated ints
                row_flat = arr[r].reshape(-1)
                f.write(" ".join(map(str, row_flat.tolist())) + "\n")
        # For grayscale (2D)
        elif arr.ndim == 2:
            H,W = arr.shape
            f.write(f"{H} {W}\n")
            for r in range(H):
                f.write(" ".join(map(str, arr[r].tolist())) + "\n")
        # For other channels (e.g., RGBA), save similarly with all channels
        else:
            shape = arr.shape
            f.write(" ".join(map(str, shape)) + "\n")
            flat = arr.reshape(-1)
            # write all values in one line (or break into rows if you prefer)
            f.write(" ".join(map(str, flat.tolist())) + "\n")
    saved['txt'] = txt_path
    print("Saved:", saved)
    return arr, saved

def load_saved_image(out_prefix="saved_image"):
    """
    Loads .npy if present, else tries to load text format saved by img_to_array.
    Returns numpy array.
    """
    npy_path = out_prefix + '.npy'
    txt_path = out_prefix + '.txt'
    if os.path.exists(npy_path):
        return np.load(npy_path)
    elif os.path.exists(txt_path):
        with open(txt_path,'r') as f:
            header = f.readline().strip().split()
            header = list(map(int, header))
            if len(header) == 2:
                H,W = header
                data = []
                for _ in range(H):
                    row = list(map(int, f.readline().strip().split()))
                    data.append(row)
                return np.array(data)
            elif len(header) == 3:
                H,W,C = header
                rows = []
                for _ in range(H):
                    vals = list(map(int, f.readline().strip().split()))
                    row = np.array(vals).reshape(W,C)
                    rows.append(row)
                return np.array(rows)
            else:
                # fallback: read remaining all numbers
                content = f.read().strip().split()
                return np.array(list(map(int, content))).reshape(header)
    else:
        raise FileNotFoundError("No saved image found with given prefix")

# Demo usage:
# Upload an image to Colab (use the left Files panel or files.upload)
# Example (uncomment and change path):
arr, saved = img_to_array('/content/download.jpeg', out_prefix='/content/saved_image')
loaded = load_saved_image('/content/saved_image')
print("Loaded shape:", loaded.shape)


Saved: {'npy': '/content/saved_image.npy', 'txt': '/content/saved_image.txt'}
Loaded shape: (920, 736, 3)
